version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: soporte-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: PNC-Final
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: soporte-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PNC-Final
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    restart: on-failure

volumes:
  postgres-data:
